"""Add relationships

Revision ID: 11b3692dbea3
Revises: 53f5d8c9905b
Create Date: 2024-07-05 00:38:15.809215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b3692dbea3'
down_revision = '53f5d8c9905b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_category', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('Fk_categories', 'categories', ['id_category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('Fk_categories', type_='foreignkey')
        batch_op.drop_column('id_category')

    # ### end Alembic commands ###
