"""Add LogsAuditoria

Revision ID: ac4689563fa3
Revises: 11b3692dbea3
Create Date: 2024-07-05 00:46:27.344850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4689563fa3'
down_revision = '11b3692dbea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
