
version: '3'

services:
  backend:
    container_name: "backend"
    command: ["flask", "--app", "main.py", "run", "--host=0.0.0.0", "--port=3000"]
    restart: always
    build: .
    volumes:
      - ./src:/app
      - ./src/camera:/app/camera
    ports:
      - "3000:3000"

  websocket:
    container_name: "websocket"
    command: ["python" ,"-u","receive_stream.py"]
    restart: always
    build:
      dockerfile: Dockerfile.websocket
    volumes:
      - ./src/websocket:/app
      - ./src/camera:/app/camera
    ports:
      - "5000:5000"
      
      